# The MIT License (MIT)
#
# Copyright © 2025 linuxdaemon <linuxdaemon.irc@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

version: "2"

run:
  concurrency: 4
  timeout: 5m

linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gochecknoinits
    - godot
    - ireturn
    - mnd
    - nlreturn
    - noinlineerr
    - paralleltest
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        # - experimental
        # - opinionated
        - performance
        # - style
    gocyclo:
      min-complexity: 10
    govet:
      enable:
        - shadow
    revive:
      rules:
        - name: argument-limit
        - name: cognitive-complexity
          arguments:
            - 16
        - name: confusing-naming
        - name: context-as-argument
        - name: context-keys-type
        - name: cyclomatic
          arguments:
            - 10
        - name: empty-lines
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: line-length-limit
          arguments:
            - 100
        - name: max-public-structs
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: package-comments
        - name: range
        - name: range-val-in-closure
        - name: time-naming
        - name: var-declaration
        - name: var-naming
        - name: waitgroup-by-value
    staticcheck:
      checks:
        - all
  exclusions:
    warn-unused: true
    generated: strict
    rules:
      - path: _test.go
        linters:
          - gosec
      - path: cmd/root.go
        linters:
          - gochecknoglobals
          - lll
        text: "rootCmd|cfgFile"
      - path: cmd/prune.go
        linters:
          - gochecknoglobals
        text: "pruneCmd"
      - path: internal/retention/policy.go
        linters:
          - gochecknoglobals
        text: "hourGrouper|dayGrouper|weekGrouper|monthGrouper|yearGrouper"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - "github.com/TotallyNotRobots/apply-retention-policy"
    golines:
      max-len: 100
      tab-len: 4
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: true

  exclusions:
    warn-unused: true
    generated: strict

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  path-prefix: ""
  path-mode: "abs"
  sort-order:
    - linter
    - severity
    - file
  show-stats: false
