# The MIT License (MIT)
#
# Copyright © 2025 linuxdaemon <linuxdaemon.irc@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

version: "2"

run:
  concurrency: 4
  timeout: 5m

linters:
  enable:
    - revive
    - gosec
    - staticcheck
    - ineffassign
    - unconvert
    - unparam
    - unused
    - whitespace
    - errcheck
    - gocyclo
    - govet
    - lll
    - dupl
    - gochecknoglobals
    - wsl
    - forbidigo
    - gocognit
    - gocritic
    - gocyclo
    - goconst
    - gosec
    - govet
  settings:
    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
        - name: error-strings
        - name: error-naming
        - name: context-keys-type
        - name: context-as-argument
        - name: time-naming
        - name: var-declaration
        - name: range
        - name: range-val-in-closure
        - name: waitgroup-by-value
        - name: empty-lines
        - name: line-length-limit
          arguments:
            - 100
        - name: argument-limit
        - name: cyclomatic
          arguments:
            - 15
        - name: max-public-structs
        - name: file-header
          arguments:
            - Copyright © 2025 linuxdaemon <linuxdaemon.irc@gmail.com>
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 3
    govet:
      enable:
        - shadow
    staticcheck:
      checks:
        - all
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    warn-unused: true
    generated: lax
    rules:
      - path: cmd/root.go
        linters:
          - gochecknoglobals
          - lll
        text: "rootCmd|cfgFile"
      - path: cmd/prune.go
        linters:
          - gochecknoglobals
        text: "pruneCmd"
      - path: internal/retention/policy.go
        linters:
          - gochecknoglobals
        text: "hourGrouper|dayGrouper|weekGrouper|monthGrouper|yearGrouper"
      - path: pkg/logger/logger.go
        linters:
          - gochecknoglobals
        text: "syncErrorOnce|isTestMode"

formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
      - "github.com/TotallyNotRobots/apply-retention-policy"
    golines:
      max-len: 100
      tab-len: 4
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: true

  exclusions:
    warn-unused: true
    generated: strict

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  path-prefix: ""
  path-mode: "abs"
  sort-order:
    - linter
    - severity
    - file
  show-stats: false
