name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per run.
          disk-cache: ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}
          # Share repository cache between workflows.
          repository-cache: true
          bazelrc: |
            common --lockfile_mode=error

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build apply-retention-policy
        shell: bash
        run: |
          set -e
          bazel build //:release_files --define=version=${{ steps.get_version.outputs.version }}
          mkdir -p out
          ls -l
          ls -l bazel-bin/
          cd out

          cp ../bazel-bin/apply-retention-policy-*.tar.gz .
          cp ../bazel-bin/apply-retention-policy-*.zip .

      - name: Make checksums
        working-directory: out
        run: |
          sha256sum * > SHA256SUMS

      - name: Build and push multi-arch image
        run: |
          bazel run //:push -- \
            --tag=${{ steps.get_version.outputs.version }} \
            --tag=latest
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          draft: false
          name: Release ${{ steps.get_version.outputs.version }}
          files: out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
